kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: postgres-data
spec:
   accessModes:
     - ReadWriteMany
   storageClassName: px-postgres-sc
   resources:
     requests:
       storage: 1Gi
