---
- name: Copy SSH Key to vagrant | [opeomotayo]
  become: yes
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '/Users/opeomotayo/.ssh/id_rsa.pub') }}"
  with_items:
    - "{{ ssh.users }}"
...
