# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  NodeCount = 1

  (1..NodeCount).each do |i|
    config.vm.define "teamcity0#{i}" do |node|
      node.vm.box = "ubuntu/bionic64"
      node.vm.hostname = "teamcity"
      node.vm.network "private_network", ip: "192.168.70.10#{i}"
      node.vbguest.installer_options = { allow_kernel_upgrade: true }
      node.vagrant.plugins = "vagrant-docker-compose"
      node.vm.provision :docker
    #   node.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", rebuild: true, run: "always"
      node.vm.provision "docker" do |d|    
        d.pull_images "jetbrains/teamcity-server"    
        d.pull_images "jetbrains/teamcity-agent"  
      end
      node.vm.provider "virtualbox" do |v|
        v.name = "teamcity0#{i}"
        v.memory = 4096
        v.cpus = 3
      end
    end
  end

end
