# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|
    config.vm.provision "shell", path: "install-k8s/bootstrap.sh"

    # Kubernetes Master Server
    config.vm.define "pwxmaster" do |pwxmaster|
        file_to_disk1 = "disks/sdb_disk_master.vdi"
        pwxmaster.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        pwxmaster.vm.box = "centos/7"
        pwxmaster.vm.hostname = "pwxmaster"
        pwxmaster.vm.network :private_network, ip: "192.168.80.10"
        pwxmaster.vbguest.installer_options = { allow_kernel_upgrade: true }
        pwxmaster.vm.provider "virtualbox" do |vb|

            unless File.exist?(file_to_disk1)
                vb.customize ['createhd', '--filename', file_to_disk1, '--variant', 'Fixed', '--size', 5 * 1024]
            end
            vb.customize ['storageattach', :id,  '--storagectl', "IDE", '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk1]
        
            vb.memory = "2048"
            vb.name = "pwxmaster"
            vb.cpus = 2
        end
        pwxmaster.vm.provision "shell", path: "install-k8s/bootstrap_pwxmaster.sh"
    end

    # Kubernetes Worker Nodes
    (1..3).each do |i|
        config.vm.define "pwxetcd#{i}" do |pwxetcd|
            file_to_disk1 = "disks/sdb_disk_worker#{i}.vdi"
            file_to_disk2 = "disks/sdc_disk_worker#{i}.vdi"
            pwxetcd.vm.synced_folder ".", "/vagrant", type: "virtualbox"
            pwxetcd.vm.box = "centos/7"
            pwxetcd.vm.hostname = "pwxetcd#{i}"
            pwxetcd.vm.network :private_network, ip: "192.168.80.1#{i}"
            pwxetcd.vbguest.installer_options = { allow_kernel_upgrade: true }
            # pwxetcd.vm.provision :ansible, playbook: "install-etcd/etcd-playbook.yaml"
            pwxetcd.vm.provider "virtualbox" do |vb|
                unless File.exist?(file_to_disk1)
                    vb.customize ['createhd', '--filename', file_to_disk1, '--variant', 'Fixed', '--size', 32 * 1024]
                end
                vb.customize ['storageattach', :id,  '--storagectl', "IDE", '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk1]
            
                unless File.exist?(file_to_disk2)
                   vb.customize ['createhd', '--filename', file_to_disk2, '--variant', 'Fixed', '--size', 8 * 1024]
                end
                vb.customize ['storageattach', :id,  '--storagectl', "IDE", '--port', 1, '--device', 1, '--type', 'hdd', '--medium', file_to_disk2]

                vb.memory = "6144"
                vb.name = "pwxetcd#{i}"
                vb.cpus = 4
            end
            pwxetcd.vm.provision "shell", path: "install-k8s/bootstrap_pwxetcd.sh"
    end
end

end


#kubectl taint nodes node1 node-role.kubernetes.io/master:NoSchedule-
#kubectl -n=kube-system scale statefulset px-etcd --replicas=3

