# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  NodeCount = 1

  (1..NodeCount).each do |i|
    config.vm.define "ranchervm0#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "ranchervm0#{i}"
      node.vm.network "private_network", ip: "192.168.71.10#{i}"
      node.vbguest.installer_options = { allow_kernel_upgrade: true }
      node.vm.provision :docker
      node.vagrant.plugins = "vagrant-docker-compose"
      node.vm.provider "virtualbox" do |v|
        v.name = "ranchervm0#{i}"
        v.memory = 4096
        v.cpus = 2
      end
    end
  end

end