# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "inclusivedesign/windows10-eval-x64"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.hostname = "teamcitywindows"
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600

  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp"
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
  # config.vm.network "private_network", ip: "192.168.93.10"
  # config.vm.network "public_network"
  config.vm.synced_folder "./", "/vagrant_data"

  config.vm.provider "virtualbox" do |vm|
      vm.name = "teamcitywindows"
      vm.gui = true
      vm.cpus = 2
      vm.memory = 4096
  end
end
